# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a197d4f74f5076a5b431f5080aaf8f47d4bc2c308d40d5686f975ac083db85537092ea2621786d7d194acbe7b833902b847873d74ef99e1cd71aa0c533c16ae

test:
  secret_key_base: f63187fda7ffb12cf6e368b0e721b042236dfb3e1e2035c04669a221139be98212ee72a688c658c807425d89a217e359ab105327104b07f9220dfd3d72de3728

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
